USE navacom;

CREATE TABLE CATEGORY (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL
);	

CREATE TABLE TOPIC (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATE BIGINT NOT NULL,
	TITLE VARCHAR(200) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	URL VARCHAR(500) NOT NULL,
	HEAD_IMAGE VARCHAR(500) NULL,
	ICON_IMAGE VARCHAR(500) NULL,
	FK_CATEGORY BIGINT NULL,
	CONSTRAINT TOPIC_FK_CATEGORY FOREIGN KEY (FK_CATEGORY) REFERENCES CATEGORY(ID)
	
);

CREATE TABLE USER (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	LASTNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE COMMENT (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATE BIGINT NOT NULL,
	TEXT VARCHAR(2500) NOT NULL,
	FK_USER BIGINT NOT NULL,
	FK_TOPIC BIGINT NOT NULL,
	CONSTRAINT COMMENT_FK_USER FOREIGN KEY (FK_USER) REFERENCES USER(ID),
	CONSTRAINT COMMENT_FK_TOPIC FOREIGN KEY (FK_TOPIC) REFERENCES TOPIC(ID)
);
